### ISSUE TITLE
Contributing updates: 8th June 2021

### ISSUE THREAD

**Issue by aldy505** [thebearingedge/node-tinyhttp-realworld-example-app#1]
I'll be working on `GET /api/articles` first, then I'll try to continue doing `DELETE /api/articles/:slug` and `GET /api/articles/feed`. 

I'll also make a README/CONTRIBUTING about development setup as I found Node v16 to be not working as it gives a few errors like these:

```bash
node:1535) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/reinaldyrfl/repository/node-tinyhttp-realworld-example-app/package.json' of 'index.mjs'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1535) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
listening on port 3000
/home/reinaldyrfl/.fnm/node-versions/v16.3.0/installation/bin/node[1535]: ../src/node_http_parser.cc:567:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
 1: 0xb17ec0 node::Abort() [/home/reinaldyrfl/.fnm/node-versions/v16.3.0/installation/bin/node]
 2: 0xb17f3e  [/home/reinaldyrfl/.fnm/node-versions/v16.3.0/installation/bin/node]
 3: 0xb2f572  [/home/reinaldyrfl/.fnm/node-versions/v16.3.0/installation/bin/node]
 4: 0xd655cb  [/home/reinaldyrfl/.fnm/node-versions/v16.3.0/installation/bin/node]
 5: 0xd66a6c  [/home/reinaldyrfl/.fnm/node-versions/v16.3.0/installation/bin/node]
 6: 0xd670e6 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/reinaldyrfl/.fnm/node-versions/v16.3.0/installation/bin/node]
 7: 0x16148d9  [/home/reinaldyrfl/.fnm/node-versions/v16.3.0/installation/bin/node]
```

On another note: I'll create one Github Actions for testing on the fly. I'd suggest you to set up a Codecov for this repo.

You can contact me via [telegram](https://t.me/aldy505) if you want to have a long chat rather than Github Issues. Cheers!

**Comment by thebearingedge** [comment]
@aldy505 Wow, this is fantastic, thanks for the assist! I'll be reviewing #2 more closely later this week.

Cheers!

**Comment by thebearingedge** [comment]
@aldy505 cc @talentlessguy,

Thanks for checking in on the progress and @aldy505 for #2 . It's merged. I'm not going to be available to work on this any more as I'm starting a new project at work. For better or worse, I work a lot of extra hours, since I teach during the day and do curriculum development off-hours. Unfortunately I just don't have the extra brain power to extend to this project.

FWIW, I've given you both push access and thank you very much for the collaboration and opportunity to contribute. I learned a lot that I'll be incorporating in future projects.
